// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgType.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_MsgType_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_MsgType_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_MsgType_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_MsgType_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_MsgType_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum PBMsgType : int {
  InvalidMsgType = 0,
  HeartbeatMsgType = 1,
  QuoteSubscribeTickMsgType = 2,
  QuoteUnsubscribeTickMsgType = 3,
  QuotePushTickMsgType = 4,
  PBMsgType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  PBMsgType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool PBMsgType_IsValid(int value);
extern const uint32_t PBMsgType_internal_data_[];
constexpr PBMsgType PBMsgType_MIN = static_cast<PBMsgType>(0);
constexpr PBMsgType PBMsgType_MAX = static_cast<PBMsgType>(4);
constexpr int PBMsgType_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor*
PBMsgType_descriptor();
template <typename T>
const std::string& PBMsgType_Name(T value) {
  static_assert(std::is_same<T, PBMsgType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PBMsgType_Name().");
  return PBMsgType_Name(static_cast<PBMsgType>(value));
}
template <>
inline const std::string& PBMsgType_Name(PBMsgType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PBMsgType_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool PBMsgType_Parse(absl::string_view name, PBMsgType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PBMsgType>(
      PBMsgType_descriptor(), name, value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::PBMsgType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::PBMsgType>() {
  return ::PBMsgType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_MsgType_2eproto_2epb_2eh
