// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Req.proto

#include "Req.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr PBReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        reqid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        payload_{nullptr},
        reqtime_{::uint64_t{0u}},
        reqmsgtype_{static_cast< ::PBMsgType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR PBReq::PBReq(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PBReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBReqDefaultTypeInternal() {}
  union {
    PBReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBReqDefaultTypeInternal _PBReq_default_instance_;
static ::_pb::Metadata file_level_metadata_Req_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Req_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Req_2eproto = nullptr;
const ::uint32_t TableStruct_Req_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::PBReq, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::PBReq, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::PBReq, _impl_.reqmsgtype_),
    PROTOBUF_FIELD_OFFSET(::PBReq, _impl_.reqid_),
    PROTOBUF_FIELD_OFFSET(::PBReq, _impl_.reqtime_),
    PROTOBUF_FIELD_OFFSET(::PBReq, _impl_.payload_),
    ~0u,
    ~0u,
    ~0u,
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 12, -1, sizeof(::PBReq)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_PBReq_default_instance_._instance,
};
const char descriptor_table_protodef_Req_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\tReq.proto\032\031google/protobuf/any.proto\032\r"
    "MsgType.proto\"n\n\005PBReq\022\036\n\nreqMsgType\030\001 \001"
    "(\0162\n.PBMsgType\022\r\n\005reqId\030\002 \001(\t\022\017\n\007reqTime"
    "\030\003 \001(\004\022%\n\007payload\030\004 \001(\0132\024.google.protobu"
    "f.Anyb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_Req_2eproto_deps[2] =
    {
        &::descriptor_table_MsgType_2eproto,
        &::descriptor_table_google_2fprotobuf_2fany_2eproto,
};
static ::absl::once_flag descriptor_table_Req_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Req_2eproto = {
    false,
    false,
    173,
    descriptor_table_protodef_Req_2eproto,
    "Req.proto",
    &descriptor_table_Req_2eproto_once,
    descriptor_table_Req_2eproto_deps,
    2,
    1,
    schemas,
    file_default_instances,
    TableStruct_Req_2eproto::offsets,
    file_level_metadata_Req_2eproto,
    file_level_enum_descriptors_Req_2eproto,
    file_level_service_descriptors_Req_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Req_2eproto_getter() {
  return &descriptor_table_Req_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Req_2eproto(&descriptor_table_Req_2eproto);
// ===================================================================

class PBReq::_Internal {
 public:
  using HasBits = decltype(std::declval<PBReq>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(PBReq, _impl_._has_bits_);
  static const ::google::protobuf::Any& payload(const PBReq* msg);
  static void set_has_payload(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::google::protobuf::Any& PBReq::_Internal::payload(const PBReq* msg) {
  return *msg->_impl_.payload_;
}
void PBReq::clear_payload() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.payload_ != nullptr) _impl_.payload_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
PBReq::PBReq(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PBReq)
}
inline PROTOBUF_NDEBUG_INLINE PBReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        reqid_(arena, from.reqid_) {}

PBReq::PBReq(
    ::google::protobuf::Arena* arena,
    const PBReq& from)
    : ::google::protobuf::Message(arena) {
  PBReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.payload_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::google::protobuf::Any>(arena, *from._impl_.payload_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, reqtime_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, reqtime_),
           offsetof(Impl_, reqmsgtype_) -
               offsetof(Impl_, reqtime_) +
               sizeof(Impl_::reqmsgtype_));

  // @@protoc_insertion_point(copy_constructor:PBReq)
}
inline PROTOBUF_NDEBUG_INLINE PBReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        reqid_(arena) {}

inline void PBReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, payload_),
           0,
           offsetof(Impl_, reqmsgtype_) -
               offsetof(Impl_, payload_) +
               sizeof(Impl_::reqmsgtype_));
}
PBReq::~PBReq() {
  // @@protoc_insertion_point(destructor:PBReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PBReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.reqid_.Destroy();
  delete _impl_.payload_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PBReq::Clear() {
// @@protoc_insertion_point(message_clear_start:PBReq)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.reqid_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.payload_ != nullptr);
    _impl_.payload_->Clear();
  }
  ::memset(&_impl_.reqtime_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.reqmsgtype_) -
      reinterpret_cast<char*>(&_impl_.reqtime_)) + sizeof(_impl_.reqmsgtype_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PBReq::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 19, 2> PBReq::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PBReq, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_PBReq_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .google.protobuf.Any payload = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 0, 0, PROTOBUF_FIELD_OFFSET(PBReq, _impl_.payload_)}},
    // .PBMsgType reqMsgType = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PBReq, _impl_.reqmsgtype_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PBReq, _impl_.reqmsgtype_)}},
    // string reqId = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PBReq, _impl_.reqid_)}},
    // uint64 reqTime = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PBReq, _impl_.reqtime_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(PBReq, _impl_.reqtime_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .PBMsgType reqMsgType = 1;
    {PROTOBUF_FIELD_OFFSET(PBReq, _impl_.reqmsgtype_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string reqId = 2;
    {PROTOBUF_FIELD_OFFSET(PBReq, _impl_.reqid_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint64 reqTime = 3;
    {PROTOBUF_FIELD_OFFSET(PBReq, _impl_.reqtime_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // .google.protobuf.Any payload = 4;
    {PROTOBUF_FIELD_OFFSET(PBReq, _impl_.payload_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Any>()},
  }}, {{
    "\5\0\5\0\0\0\0\0"
    "PBReq"
    "reqId"
  }},
};

::uint8_t* PBReq::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBReq)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .PBMsgType reqMsgType = 1;
  if (this->_internal_reqmsgtype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_reqmsgtype(), target);
  }

  // string reqId = 2;
  if (!this->_internal_reqid().empty()) {
    const std::string& _s = this->_internal_reqid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PBReq.reqId");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // uint64 reqTime = 3;
  if (this->_internal_reqtime() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        3, this->_internal_reqtime(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Any payload = 4;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, _Internal::payload(this),
        _Internal::payload(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBReq)
  return target;
}

::size_t PBReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBReq)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string reqId = 2;
  if (!this->_internal_reqid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_reqid());
  }

  // .google.protobuf.Any payload = 4;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.payload_);
  }

  // uint64 reqTime = 3;
  if (this->_internal_reqtime() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_reqtime());
  }

  // .PBMsgType reqMsgType = 1;
  if (this->_internal_reqmsgtype() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_reqmsgtype());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PBReq::_class_data_ = {
    PBReq::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PBReq::GetClassData() const {
  return &_class_data_;
}

void PBReq::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PBReq*>(&to_msg);
  auto& from = static_cast<const PBReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_reqid().empty()) {
    _this->_internal_set_reqid(from._internal_reqid());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_payload()->::google::protobuf::Any::MergeFrom(
        from._internal_payload());
  }
  if (from._internal_reqtime() != 0) {
    _this->_internal_set_reqtime(from._internal_reqtime());
  }
  if (from._internal_reqmsgtype() != 0) {
    _this->_internal_set_reqmsgtype(from._internal_reqmsgtype());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PBReq::CopyFrom(const PBReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PBReq::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PBReq::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PBReq::InternalSwap(PBReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reqid_, &other->_impl_.reqid_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PBReq, _impl_.reqmsgtype_)
      + sizeof(PBReq::_impl_.reqmsgtype_)
      - PROTOBUF_FIELD_OFFSET(PBReq, _impl_.payload_)>(
          reinterpret_cast<char*>(&_impl_.payload_),
          reinterpret_cast<char*>(&other->_impl_.payload_));
}

::google::protobuf::Metadata PBReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Req_2eproto_getter, &descriptor_table_Req_2eproto_once,
      file_level_metadata_Req_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
