// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Res.proto

#include "Res.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr PBRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        reqid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        retmsg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        payload_{nullptr},
        resmsgtype_{static_cast< ::PBMsgType >(0)},
        retcode_{0},
        restime_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR PBRes::PBRes(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PBResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PBResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PBResDefaultTypeInternal() {}
  union {
    PBRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PBResDefaultTypeInternal _PBRes_default_instance_;
static ::_pb::Metadata file_level_metadata_Res_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_Res_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Res_2eproto = nullptr;
const ::uint32_t TableStruct_Res_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::PBRes, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::PBRes, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::PBRes, _impl_.resmsgtype_),
    PROTOBUF_FIELD_OFFSET(::PBRes, _impl_.reqid_),
    PROTOBUF_FIELD_OFFSET(::PBRes, _impl_.restime_),
    PROTOBUF_FIELD_OFFSET(::PBRes, _impl_.retcode_),
    PROTOBUF_FIELD_OFFSET(::PBRes, _impl_.retmsg_),
    PROTOBUF_FIELD_OFFSET(::PBRes, _impl_.payload_),
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 14, -1, sizeof(::PBRes)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_PBRes_default_instance_._instance,
};
const char descriptor_table_protodef_Res_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\tRes.proto\032\031google/protobuf/any.proto\032\r"
    "MsgType.proto\"\217\001\n\005PBRes\022\036\n\nresMsgType\030\001 "
    "\001(\0162\n.PBMsgType\022\r\n\005reqId\030\002 \001(\t\022\017\n\007resTim"
    "e\030\003 \001(\004\022\017\n\007retCode\030\004 \001(\005\022\016\n\006retMsg\030\005 \001(\t"
    "\022%\n\007payload\030\006 \001(\0132\024.google.protobuf.Anyb"
    "\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_Res_2eproto_deps[2] =
    {
        &::descriptor_table_MsgType_2eproto,
        &::descriptor_table_google_2fprotobuf_2fany_2eproto,
};
static ::absl::once_flag descriptor_table_Res_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Res_2eproto = {
    false,
    false,
    207,
    descriptor_table_protodef_Res_2eproto,
    "Res.proto",
    &descriptor_table_Res_2eproto_once,
    descriptor_table_Res_2eproto_deps,
    2,
    1,
    schemas,
    file_default_instances,
    TableStruct_Res_2eproto::offsets,
    file_level_metadata_Res_2eproto,
    file_level_enum_descriptors_Res_2eproto,
    file_level_service_descriptors_Res_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Res_2eproto_getter() {
  return &descriptor_table_Res_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Res_2eproto(&descriptor_table_Res_2eproto);
// ===================================================================

class PBRes::_Internal {
 public:
  using HasBits = decltype(std::declval<PBRes>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(PBRes, _impl_._has_bits_);
  static const ::google::protobuf::Any& payload(const PBRes* msg);
  static void set_has_payload(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::google::protobuf::Any& PBRes::_Internal::payload(const PBRes* msg) {
  return *msg->_impl_.payload_;
}
void PBRes::clear_payload() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.payload_ != nullptr) _impl_.payload_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
PBRes::PBRes(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PBRes)
}
inline PROTOBUF_NDEBUG_INLINE PBRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        reqid_(arena, from.reqid_),
        retmsg_(arena, from.retmsg_) {}

PBRes::PBRes(
    ::google::protobuf::Arena* arena,
    const PBRes& from)
    : ::google::protobuf::Message(arena) {
  PBRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.payload_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::google::protobuf::Any>(arena, *from._impl_.payload_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, resmsgtype_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, resmsgtype_),
           offsetof(Impl_, restime_) -
               offsetof(Impl_, resmsgtype_) +
               sizeof(Impl_::restime_));

  // @@protoc_insertion_point(copy_constructor:PBRes)
}
inline PROTOBUF_NDEBUG_INLINE PBRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        reqid_(arena),
        retmsg_(arena) {}

inline void PBRes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, payload_),
           0,
           offsetof(Impl_, restime_) -
               offsetof(Impl_, payload_) +
               sizeof(Impl_::restime_));
}
PBRes::~PBRes() {
  // @@protoc_insertion_point(destructor:PBRes)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PBRes::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.reqid_.Destroy();
  _impl_.retmsg_.Destroy();
  delete _impl_.payload_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PBRes::Clear() {
// @@protoc_insertion_point(message_clear_start:PBRes)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.reqid_.ClearToEmpty();
  _impl_.retmsg_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.payload_ != nullptr);
    _impl_.payload_->Clear();
  }
  ::memset(&_impl_.resmsgtype_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.restime_) -
      reinterpret_cast<char*>(&_impl_.resmsgtype_)) + sizeof(_impl_.restime_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PBRes::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 1, 25, 2> PBRes::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PBRes, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_PBRes_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .PBMsgType resMsgType = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PBRes, _impl_.resmsgtype_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PBRes, _impl_.resmsgtype_)}},
    // string reqId = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PBRes, _impl_.reqid_)}},
    // uint64 resTime = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PBRes, _impl_.restime_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(PBRes, _impl_.restime_)}},
    // int32 retCode = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PBRes, _impl_.retcode_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(PBRes, _impl_.retcode_)}},
    // string retMsg = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(PBRes, _impl_.retmsg_)}},
    // .google.protobuf.Any payload = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 0, 0, PROTOBUF_FIELD_OFFSET(PBRes, _impl_.payload_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .PBMsgType resMsgType = 1;
    {PROTOBUF_FIELD_OFFSET(PBRes, _impl_.resmsgtype_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string reqId = 2;
    {PROTOBUF_FIELD_OFFSET(PBRes, _impl_.reqid_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint64 resTime = 3;
    {PROTOBUF_FIELD_OFFSET(PBRes, _impl_.restime_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // int32 retCode = 4;
    {PROTOBUF_FIELD_OFFSET(PBRes, _impl_.retcode_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string retMsg = 5;
    {PROTOBUF_FIELD_OFFSET(PBRes, _impl_.retmsg_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.Any payload = 6;
    {PROTOBUF_FIELD_OFFSET(PBRes, _impl_.payload_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::google::protobuf::Any>()},
  }}, {{
    "\5\0\5\0\0\6\0\0"
    "PBRes"
    "reqId"
    "retMsg"
  }},
};

::uint8_t* PBRes::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PBRes)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .PBMsgType resMsgType = 1;
  if (this->_internal_resmsgtype() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_resmsgtype(), target);
  }

  // string reqId = 2;
  if (!this->_internal_reqid().empty()) {
    const std::string& _s = this->_internal_reqid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PBRes.reqId");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // uint64 resTime = 3;
  if (this->_internal_restime() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        3, this->_internal_restime(), target);
  }

  // int32 retCode = 4;
  if (this->_internal_retcode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_retcode(), target);
  }

  // string retMsg = 5;
  if (!this->_internal_retmsg().empty()) {
    const std::string& _s = this->_internal_retmsg();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PBRes.retMsg");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .google.protobuf.Any payload = 6;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        6, _Internal::payload(this),
        _Internal::payload(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBRes)
  return target;
}

::size_t PBRes::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBRes)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string reqId = 2;
  if (!this->_internal_reqid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_reqid());
  }

  // string retMsg = 5;
  if (!this->_internal_retmsg().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_retmsg());
  }

  // .google.protobuf.Any payload = 6;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.payload_);
  }

  // .PBMsgType resMsgType = 1;
  if (this->_internal_resmsgtype() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_resmsgtype());
  }

  // int32 retCode = 4;
  if (this->_internal_retcode() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_retcode());
  }

  // uint64 resTime = 3;
  if (this->_internal_restime() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_restime());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PBRes::_class_data_ = {
    PBRes::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PBRes::GetClassData() const {
  return &_class_data_;
}

void PBRes::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PBRes*>(&to_msg);
  auto& from = static_cast<const PBRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:PBRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_reqid().empty()) {
    _this->_internal_set_reqid(from._internal_reqid());
  }
  if (!from._internal_retmsg().empty()) {
    _this->_internal_set_retmsg(from._internal_retmsg());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_payload()->::google::protobuf::Any::MergeFrom(
        from._internal_payload());
  }
  if (from._internal_resmsgtype() != 0) {
    _this->_internal_set_resmsgtype(from._internal_resmsgtype());
  }
  if (from._internal_retcode() != 0) {
    _this->_internal_set_retcode(from._internal_retcode());
  }
  if (from._internal_restime() != 0) {
    _this->_internal_set_restime(from._internal_restime());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PBRes::CopyFrom(const PBRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PBRes::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PBRes::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PBRes::InternalSwap(PBRes* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.reqid_, &other->_impl_.reqid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.retmsg_, &other->_impl_.retmsg_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PBRes, _impl_.restime_)
      + sizeof(PBRes::_impl_.restime_)
      - PROTOBUF_FIELD_OFFSET(PBRes, _impl_.payload_)>(
          reinterpret_cast<char*>(&_impl_.payload_),
          reinterpret_cast<char*>(&other->_impl_.payload_));
}

::google::protobuf::Metadata PBRes::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Res_2eproto_getter, &descriptor_table_Res_2eproto_once,
      file_level_metadata_Res_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
