// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: req/HeartbeatReq.proto

#include "req/HeartbeatReq.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR HeartbeatReq::HeartbeatReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.reqindex_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HeartbeatReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartbeatReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartbeatReqDefaultTypeInternal() {}
  union {
    HeartbeatReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartbeatReqDefaultTypeInternal _HeartbeatReq_default_instance_;
static ::_pb::Metadata file_level_metadata_req_2fHeartbeatReq_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_req_2fHeartbeatReq_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_req_2fHeartbeatReq_2eproto = nullptr;

const uint32_t TableStruct_req_2fHeartbeatReq_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::HeartbeatReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::HeartbeatReq, _impl_.reqindex_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::HeartbeatReq)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_HeartbeatReq_default_instance_._instance,
};

const char descriptor_table_protodef_req_2fHeartbeatReq_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026req/HeartbeatReq.proto\" \n\014HeartbeatReq"
  "\022\020\n\010reqIndex\030\001 \001(\003b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_req_2fHeartbeatReq_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_req_2fHeartbeatReq_2eproto = {
    false, false, 66, descriptor_table_protodef_req_2fHeartbeatReq_2eproto,
    "req/HeartbeatReq.proto",
    &descriptor_table_req_2fHeartbeatReq_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_req_2fHeartbeatReq_2eproto::offsets,
    file_level_metadata_req_2fHeartbeatReq_2eproto, file_level_enum_descriptors_req_2fHeartbeatReq_2eproto,
    file_level_service_descriptors_req_2fHeartbeatReq_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_req_2fHeartbeatReq_2eproto_getter() {
  return &descriptor_table_req_2fHeartbeatReq_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_req_2fHeartbeatReq_2eproto(&descriptor_table_req_2fHeartbeatReq_2eproto);

// ===================================================================

class HeartbeatReq::_Internal {
 public:
};

HeartbeatReq::HeartbeatReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:HeartbeatReq)
}
HeartbeatReq::HeartbeatReq(const HeartbeatReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HeartbeatReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.reqindex_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.reqindex_ = from._impl_.reqindex_;
  // @@protoc_insertion_point(copy_constructor:HeartbeatReq)
}

inline void HeartbeatReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.reqindex_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

HeartbeatReq::~HeartbeatReq() {
  // @@protoc_insertion_point(destructor:HeartbeatReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HeartbeatReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void HeartbeatReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HeartbeatReq::Clear() {
// @@protoc_insertion_point(message_clear_start:HeartbeatReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.reqindex_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HeartbeatReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 reqIndex = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.reqindex_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HeartbeatReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:HeartbeatReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 reqIndex = 1;
  if (this->_internal_reqindex() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_reqindex(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HeartbeatReq)
  return target;
}

size_t HeartbeatReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HeartbeatReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 reqIndex = 1;
  if (this->_internal_reqindex() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_reqindex());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HeartbeatReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HeartbeatReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HeartbeatReq::GetClassData() const { return &_class_data_; }


void HeartbeatReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HeartbeatReq*>(&to_msg);
  auto& from = static_cast<const HeartbeatReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:HeartbeatReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_reqindex() != 0) {
    _this->_internal_set_reqindex(from._internal_reqindex());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HeartbeatReq::CopyFrom(const HeartbeatReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HeartbeatReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HeartbeatReq::IsInitialized() const {
  return true;
}

void HeartbeatReq::InternalSwap(HeartbeatReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.reqindex_, other->_impl_.reqindex_);
}

::PROTOBUF_NAMESPACE_ID::Metadata HeartbeatReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_req_2fHeartbeatReq_2eproto_getter, &descriptor_table_req_2fHeartbeatReq_2eproto_once,
      file_level_metadata_req_2fHeartbeatReq_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::HeartbeatReq*
Arena::CreateMaybeMessage< ::HeartbeatReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::HeartbeatReq >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
