// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: req/QuoteUnsubscribeTickReq.proto

#include "req/QuoteUnsubscribeTickReq.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Quote {
PROTOBUF_CONSTEXPR UnsubscribeTickReq::UnsubscribeTickReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.stocklist_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct UnsubscribeTickReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UnsubscribeTickReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~UnsubscribeTickReqDefaultTypeInternal() {}
  union {
    UnsubscribeTickReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UnsubscribeTickReqDefaultTypeInternal _UnsubscribeTickReq_default_instance_;
}  // namespace Quote
static ::_pb::Metadata file_level_metadata_req_2fQuoteUnsubscribeTickReq_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_req_2fQuoteUnsubscribeTickReq_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_req_2fQuoteUnsubscribeTickReq_2eproto = nullptr;

const uint32_t TableStruct_req_2fQuoteUnsubscribeTickReq_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Quote::UnsubscribeTickReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Quote::UnsubscribeTickReq, _impl_.stocklist_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Quote::UnsubscribeTickReq)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Quote::_UnsubscribeTickReq_default_instance_._instance,
};

const char descriptor_table_protodef_req_2fQuoteUnsubscribeTickReq_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n!req/QuoteUnsubscribeTickReq.proto\022\005Quo"
  "te\032\022common/Stock.proto\"/\n\022UnsubscribeTic"
  "kReq\022\031\n\tstockList\030\001 \003(\0132\006.Stockb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_req_2fQuoteUnsubscribeTickReq_2eproto_deps[1] = {
  &::descriptor_table_common_2fStock_2eproto,
};
static ::_pbi::once_flag descriptor_table_req_2fQuoteUnsubscribeTickReq_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_req_2fQuoteUnsubscribeTickReq_2eproto = {
    false, false, 119, descriptor_table_protodef_req_2fQuoteUnsubscribeTickReq_2eproto,
    "req/QuoteUnsubscribeTickReq.proto",
    &descriptor_table_req_2fQuoteUnsubscribeTickReq_2eproto_once, descriptor_table_req_2fQuoteUnsubscribeTickReq_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_req_2fQuoteUnsubscribeTickReq_2eproto::offsets,
    file_level_metadata_req_2fQuoteUnsubscribeTickReq_2eproto, file_level_enum_descriptors_req_2fQuoteUnsubscribeTickReq_2eproto,
    file_level_service_descriptors_req_2fQuoteUnsubscribeTickReq_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_req_2fQuoteUnsubscribeTickReq_2eproto_getter() {
  return &descriptor_table_req_2fQuoteUnsubscribeTickReq_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_req_2fQuoteUnsubscribeTickReq_2eproto(&descriptor_table_req_2fQuoteUnsubscribeTickReq_2eproto);
namespace Quote {

// ===================================================================

class UnsubscribeTickReq::_Internal {
 public:
};

void UnsubscribeTickReq::clear_stocklist() {
  _impl_.stocklist_.Clear();
}
UnsubscribeTickReq::UnsubscribeTickReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Quote.UnsubscribeTickReq)
}
UnsubscribeTickReq::UnsubscribeTickReq(const UnsubscribeTickReq& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  UnsubscribeTickReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.stocklist_){from._impl_.stocklist_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Quote.UnsubscribeTickReq)
}

inline void UnsubscribeTickReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.stocklist_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

UnsubscribeTickReq::~UnsubscribeTickReq() {
  // @@protoc_insertion_point(destructor:Quote.UnsubscribeTickReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void UnsubscribeTickReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.stocklist_.~RepeatedPtrField();
}

void UnsubscribeTickReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void UnsubscribeTickReq::Clear() {
// @@protoc_insertion_point(message_clear_start:Quote.UnsubscribeTickReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.stocklist_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* UnsubscribeTickReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .Stock stockList = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_stocklist(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* UnsubscribeTickReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Quote.UnsubscribeTickReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Stock stockList = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_stocklist_size()); i < n; i++) {
    const auto& repfield = this->_internal_stocklist(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Quote.UnsubscribeTickReq)
  return target;
}

size_t UnsubscribeTickReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Quote.UnsubscribeTickReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Stock stockList = 1;
  total_size += 1UL * this->_internal_stocklist_size();
  for (const auto& msg : this->_impl_.stocklist_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData UnsubscribeTickReq::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    UnsubscribeTickReq::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*UnsubscribeTickReq::GetClassData() const { return &_class_data_; }


void UnsubscribeTickReq::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<UnsubscribeTickReq*>(&to_msg);
  auto& from = static_cast<const UnsubscribeTickReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Quote.UnsubscribeTickReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.stocklist_.MergeFrom(from._impl_.stocklist_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void UnsubscribeTickReq::CopyFrom(const UnsubscribeTickReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Quote.UnsubscribeTickReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnsubscribeTickReq::IsInitialized() const {
  return true;
}

void UnsubscribeTickReq::InternalSwap(UnsubscribeTickReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.stocklist_.InternalSwap(&other->_impl_.stocklist_);
}

::PROTOBUF_NAMESPACE_ID::Metadata UnsubscribeTickReq::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_req_2fQuoteUnsubscribeTickReq_2eproto_getter, &descriptor_table_req_2fQuoteUnsubscribeTickReq_2eproto_once,
      file_level_metadata_req_2fQuoteUnsubscribeTickReq_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Quote
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Quote::UnsubscribeTickReq*
Arena::CreateMaybeMessage< ::Quote::UnsubscribeTickReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Quote::UnsubscribeTickReq >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
