// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: req/QuoteUnsubscribeTickReq.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_req_2fQuoteUnsubscribeTickReq_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_req_2fQuoteUnsubscribeTickReq_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common/Stock.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_req_2fQuoteUnsubscribeTickReq_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_req_2fQuoteUnsubscribeTickReq_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_req_2fQuoteUnsubscribeTickReq_2eproto;
namespace Quote {
class UnsubscribeTickReq;
struct UnsubscribeTickReqDefaultTypeInternal;
extern UnsubscribeTickReqDefaultTypeInternal _UnsubscribeTickReq_default_instance_;
}  // namespace Quote
PROTOBUF_NAMESPACE_OPEN
template<> ::Quote::UnsubscribeTickReq* Arena::CreateMaybeMessage<::Quote::UnsubscribeTickReq>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Quote {

// ===================================================================

class UnsubscribeTickReq final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Quote.UnsubscribeTickReq) */ {
 public:
  inline UnsubscribeTickReq() : UnsubscribeTickReq(nullptr) {}
  ~UnsubscribeTickReq() override;
  explicit PROTOBUF_CONSTEXPR UnsubscribeTickReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UnsubscribeTickReq(const UnsubscribeTickReq& from);
  UnsubscribeTickReq(UnsubscribeTickReq&& from) noexcept
    : UnsubscribeTickReq() {
    *this = ::std::move(from);
  }

  inline UnsubscribeTickReq& operator=(const UnsubscribeTickReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline UnsubscribeTickReq& operator=(UnsubscribeTickReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UnsubscribeTickReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const UnsubscribeTickReq* internal_default_instance() {
    return reinterpret_cast<const UnsubscribeTickReq*>(
               &_UnsubscribeTickReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(UnsubscribeTickReq& a, UnsubscribeTickReq& b) {
    a.Swap(&b);
  }
  inline void Swap(UnsubscribeTickReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UnsubscribeTickReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UnsubscribeTickReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UnsubscribeTickReq>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UnsubscribeTickReq& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UnsubscribeTickReq& from) {
    UnsubscribeTickReq::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UnsubscribeTickReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Quote.UnsubscribeTickReq";
  }
  protected:
  explicit UnsubscribeTickReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStockListFieldNumber = 1,
  };
  // repeated .Stock stockList = 1;
  int stocklist_size() const;
  private:
  int _internal_stocklist_size() const;
  public:
  void clear_stocklist();
  ::Stock* mutable_stocklist(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Stock >*
      mutable_stocklist();
  private:
  const ::Stock& _internal_stocklist(int index) const;
  ::Stock* _internal_add_stocklist();
  public:
  const ::Stock& stocklist(int index) const;
  ::Stock* add_stocklist();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Stock >&
      stocklist() const;

  // @@protoc_insertion_point(class_scope:Quote.UnsubscribeTickReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Stock > stocklist_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_req_2fQuoteUnsubscribeTickReq_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UnsubscribeTickReq

// repeated .Stock stockList = 1;
inline int UnsubscribeTickReq::_internal_stocklist_size() const {
  return _impl_.stocklist_.size();
}
inline int UnsubscribeTickReq::stocklist_size() const {
  return _internal_stocklist_size();
}
inline ::Stock* UnsubscribeTickReq::mutable_stocklist(int index) {
  // @@protoc_insertion_point(field_mutable:Quote.UnsubscribeTickReq.stockList)
  return _impl_.stocklist_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Stock >*
UnsubscribeTickReq::mutable_stocklist() {
  // @@protoc_insertion_point(field_mutable_list:Quote.UnsubscribeTickReq.stockList)
  return &_impl_.stocklist_;
}
inline const ::Stock& UnsubscribeTickReq::_internal_stocklist(int index) const {
  return _impl_.stocklist_.Get(index);
}
inline const ::Stock& UnsubscribeTickReq::stocklist(int index) const {
  // @@protoc_insertion_point(field_get:Quote.UnsubscribeTickReq.stockList)
  return _internal_stocklist(index);
}
inline ::Stock* UnsubscribeTickReq::_internal_add_stocklist() {
  return _impl_.stocklist_.Add();
}
inline ::Stock* UnsubscribeTickReq::add_stocklist() {
  ::Stock* _add = _internal_add_stocklist();
  // @@protoc_insertion_point(field_add:Quote.UnsubscribeTickReq.stockList)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Stock >&
UnsubscribeTickReq::stocklist() const {
  // @@protoc_insertion_point(field_list:Quote.UnsubscribeTickReq.stockList)
  return _impl_.stocklist_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Quote

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_req_2fQuoteUnsubscribeTickReq_2eproto
