// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notify/QuotePushTickNotify.proto

#include "notify/QuotePushTickNotify.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Quote {

inline constexpr PushTickItem::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        price_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        chg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        chgpercent_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        bid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ask_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        stock_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR PushTickItem::PushTickItem(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PushTickItemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PushTickItemDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PushTickItemDefaultTypeInternal() {}
  union {
    PushTickItem _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PushTickItemDefaultTypeInternal _PushTickItem_default_instance_;

inline constexpr PushTickNotify::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : ticklist_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PushTickNotify::PushTickNotify(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PushTickNotifyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PushTickNotifyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PushTickNotifyDefaultTypeInternal() {}
  union {
    PushTickNotify _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PushTickNotifyDefaultTypeInternal _PushTickNotify_default_instance_;
}  // namespace Quote
static ::_pb::Metadata file_level_metadata_notify_2fQuotePushTickNotify_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_notify_2fQuotePushTickNotify_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_notify_2fQuotePushTickNotify_2eproto = nullptr;
const ::uint32_t TableStruct_notify_2fQuotePushTickNotify_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::Quote::PushTickItem, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::Quote::PushTickItem, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Quote::PushTickItem, _impl_.stock_),
    PROTOBUF_FIELD_OFFSET(::Quote::PushTickItem, _impl_.price_),
    PROTOBUF_FIELD_OFFSET(::Quote::PushTickItem, _impl_.chg_),
    PROTOBUF_FIELD_OFFSET(::Quote::PushTickItem, _impl_.chgpercent_),
    PROTOBUF_FIELD_OFFSET(::Quote::PushTickItem, _impl_.bid_),
    PROTOBUF_FIELD_OFFSET(::Quote::PushTickItem, _impl_.ask_),
    0,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::Quote::PushTickNotify, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::Quote::PushTickNotify, _impl_.ticklist_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 14, -1, sizeof(::Quote::PushTickItem)},
        {20, -1, -1, sizeof(::Quote::PushTickNotify)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::Quote::_PushTickItem_default_instance_._instance,
    &::Quote::_PushTickNotify_default_instance_._instance,
};
const char descriptor_table_protodef_notify_2fQuotePushTickNotify_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n notify/QuotePushTickNotify.proto\022\005Quot"
    "e\032\022common/Stock.proto\"o\n\014PushTickItem\022\025\n"
    "\005stock\030\001 \001(\0132\006.Stock\022\r\n\005price\030\002 \001(\t\022\013\n\003c"
    "hg\030\003 \001(\t\022\022\n\nchgPercent\030\004 \001(\t\022\013\n\003bid\030\005 \001("
    "\t\022\013\n\003ask\030\006 \001(\t\"7\n\016PushTickNotify\022%\n\010tick"
    "List\030\001 \003(\0132\023.Quote.PushTickItemb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_notify_2fQuotePushTickNotify_2eproto_deps[1] =
    {
        &::descriptor_table_common_2fStock_2eproto,
};
static ::absl::once_flag descriptor_table_notify_2fQuotePushTickNotify_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_notify_2fQuotePushTickNotify_2eproto = {
    false,
    false,
    239,
    descriptor_table_protodef_notify_2fQuotePushTickNotify_2eproto,
    "notify/QuotePushTickNotify.proto",
    &descriptor_table_notify_2fQuotePushTickNotify_2eproto_once,
    descriptor_table_notify_2fQuotePushTickNotify_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_notify_2fQuotePushTickNotify_2eproto::offsets,
    file_level_metadata_notify_2fQuotePushTickNotify_2eproto,
    file_level_enum_descriptors_notify_2fQuotePushTickNotify_2eproto,
    file_level_service_descriptors_notify_2fQuotePushTickNotify_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_notify_2fQuotePushTickNotify_2eproto_getter() {
  return &descriptor_table_notify_2fQuotePushTickNotify_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_notify_2fQuotePushTickNotify_2eproto(&descriptor_table_notify_2fQuotePushTickNotify_2eproto);
namespace Quote {
// ===================================================================

class PushTickItem::_Internal {
 public:
  using HasBits = decltype(std::declval<PushTickItem>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(PushTickItem, _impl_._has_bits_);
  static const ::Stock& stock(const PushTickItem* msg);
  static void set_has_stock(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::Stock& PushTickItem::_Internal::stock(const PushTickItem* msg) {
  return *msg->_impl_.stock_;
}
void PushTickItem::clear_stock() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.stock_ != nullptr) _impl_.stock_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
PushTickItem::PushTickItem(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Quote.PushTickItem)
}
inline PROTOBUF_NDEBUG_INLINE PushTickItem::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        price_(arena, from.price_),
        chg_(arena, from.chg_),
        chgpercent_(arena, from.chgpercent_),
        bid_(arena, from.bid_),
        ask_(arena, from.ask_) {}

PushTickItem::PushTickItem(
    ::google::protobuf::Arena* arena,
    const PushTickItem& from)
    : ::google::protobuf::Message(arena) {
  PushTickItem* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.stock_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::Stock>(arena, *from._impl_.stock_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:Quote.PushTickItem)
}
inline PROTOBUF_NDEBUG_INLINE PushTickItem::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        price_(arena),
        chg_(arena),
        chgpercent_(arena),
        bid_(arena),
        ask_(arena) {}

inline void PushTickItem::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.stock_ = {};
}
PushTickItem::~PushTickItem() {
  // @@protoc_insertion_point(destructor:Quote.PushTickItem)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PushTickItem::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.price_.Destroy();
  _impl_.chg_.Destroy();
  _impl_.chgpercent_.Destroy();
  _impl_.bid_.Destroy();
  _impl_.ask_.Destroy();
  delete _impl_.stock_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PushTickItem::Clear() {
// @@protoc_insertion_point(message_clear_start:Quote.PushTickItem)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.price_.ClearToEmpty();
  _impl_.chg_.ClearToEmpty();
  _impl_.chgpercent_.ClearToEmpty();
  _impl_.bid_.ClearToEmpty();
  _impl_.ask_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.stock_ != nullptr);
    _impl_.stock_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PushTickItem::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 1, 51, 2> PushTickItem::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PushTickItem, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_PushTickItem_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .Stock stock = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(PushTickItem, _impl_.stock_)}},
    // string price = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PushTickItem, _impl_.price_)}},
    // string chg = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(PushTickItem, _impl_.chg_)}},
    // string chgPercent = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(PushTickItem, _impl_.chgpercent_)}},
    // string bid = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(PushTickItem, _impl_.bid_)}},
    // string ask = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(PushTickItem, _impl_.ask_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .Stock stock = 1;
    {PROTOBUF_FIELD_OFFSET(PushTickItem, _impl_.stock_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string price = 2;
    {PROTOBUF_FIELD_OFFSET(PushTickItem, _impl_.price_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string chg = 3;
    {PROTOBUF_FIELD_OFFSET(PushTickItem, _impl_.chg_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string chgPercent = 4;
    {PROTOBUF_FIELD_OFFSET(PushTickItem, _impl_.chgpercent_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string bid = 5;
    {PROTOBUF_FIELD_OFFSET(PushTickItem, _impl_.bid_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string ask = 6;
    {PROTOBUF_FIELD_OFFSET(PushTickItem, _impl_.ask_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Stock>()},
  }}, {{
    "\22\0\5\3\12\3\3\0"
    "Quote.PushTickItem"
    "price"
    "chg"
    "chgPercent"
    "bid"
    "ask"
  }},
};

::uint8_t* PushTickItem::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Quote.PushTickItem)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // .Stock stock = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, _Internal::stock(this),
        _Internal::stock(this).GetCachedSize(), target, stream);
  }

  // string price = 2;
  if (!this->_internal_price().empty()) {
    const std::string& _s = this->_internal_price();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Quote.PushTickItem.price");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string chg = 3;
  if (!this->_internal_chg().empty()) {
    const std::string& _s = this->_internal_chg();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Quote.PushTickItem.chg");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string chgPercent = 4;
  if (!this->_internal_chgpercent().empty()) {
    const std::string& _s = this->_internal_chgpercent();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Quote.PushTickItem.chgPercent");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // string bid = 5;
  if (!this->_internal_bid().empty()) {
    const std::string& _s = this->_internal_bid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Quote.PushTickItem.bid");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // string ask = 6;
  if (!this->_internal_ask().empty()) {
    const std::string& _s = this->_internal_ask();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Quote.PushTickItem.ask");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Quote.PushTickItem)
  return target;
}

::size_t PushTickItem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Quote.PushTickItem)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string price = 2;
  if (!this->_internal_price().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_price());
  }

  // string chg = 3;
  if (!this->_internal_chg().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_chg());
  }

  // string chgPercent = 4;
  if (!this->_internal_chgpercent().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_chgpercent());
  }

  // string bid = 5;
  if (!this->_internal_bid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_bid());
  }

  // string ask = 6;
  if (!this->_internal_ask().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_ask());
  }

  // .Stock stock = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.stock_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PushTickItem::_class_data_ = {
    PushTickItem::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PushTickItem::GetClassData() const {
  return &_class_data_;
}

void PushTickItem::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PushTickItem*>(&to_msg);
  auto& from = static_cast<const PushTickItem&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Quote.PushTickItem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_price().empty()) {
    _this->_internal_set_price(from._internal_price());
  }
  if (!from._internal_chg().empty()) {
    _this->_internal_set_chg(from._internal_chg());
  }
  if (!from._internal_chgpercent().empty()) {
    _this->_internal_set_chgpercent(from._internal_chgpercent());
  }
  if (!from._internal_bid().empty()) {
    _this->_internal_set_bid(from._internal_bid());
  }
  if (!from._internal_ask().empty()) {
    _this->_internal_set_ask(from._internal_ask());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_stock()->::Stock::MergeFrom(
        from._internal_stock());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PushTickItem::CopyFrom(const PushTickItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Quote.PushTickItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PushTickItem::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PushTickItem::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PushTickItem::InternalSwap(PushTickItem* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.price_, &other->_impl_.price_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.chg_, &other->_impl_.chg_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.chgpercent_, &other->_impl_.chgpercent_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.bid_, &other->_impl_.bid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ask_, &other->_impl_.ask_, arena);
  swap(_impl_.stock_, other->_impl_.stock_);
}

::google::protobuf::Metadata PushTickItem::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_notify_2fQuotePushTickNotify_2eproto_getter, &descriptor_table_notify_2fQuotePushTickNotify_2eproto_once,
      file_level_metadata_notify_2fQuotePushTickNotify_2eproto[0]);
}
// ===================================================================

class PushTickNotify::_Internal {
 public:
};

PushTickNotify::PushTickNotify(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Quote.PushTickNotify)
}
inline PROTOBUF_NDEBUG_INLINE PushTickNotify::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : ticklist_{visibility, arena, from.ticklist_},
        _cached_size_{0} {}

PushTickNotify::PushTickNotify(
    ::google::protobuf::Arena* arena,
    const PushTickNotify& from)
    : ::google::protobuf::Message(arena) {
  PushTickNotify* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:Quote.PushTickNotify)
}
inline PROTOBUF_NDEBUG_INLINE PushTickNotify::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : ticklist_{visibility, arena},
        _cached_size_{0} {}

inline void PushTickNotify::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PushTickNotify::~PushTickNotify() {
  // @@protoc_insertion_point(destructor:Quote.PushTickNotify)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PushTickNotify::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PushTickNotify::Clear() {
// @@protoc_insertion_point(message_clear_start:Quote.PushTickNotify)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ticklist_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PushTickNotify::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> PushTickNotify::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_PushTickNotify_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .Quote.PushTickItem tickList = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PushTickNotify, _impl_.ticklist_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .Quote.PushTickItem tickList = 1;
    {PROTOBUF_FIELD_OFFSET(PushTickNotify, _impl_.ticklist_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::Quote::PushTickItem>()},
  }}, {{
  }},
};

::uint8_t* PushTickNotify::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Quote.PushTickNotify)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .Quote.PushTickItem tickList = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_ticklist_size()); i < n; i++) {
    const auto& repfield = this->_internal_ticklist().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Quote.PushTickNotify)
  return target;
}

::size_t PushTickNotify::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Quote.PushTickNotify)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Quote.PushTickItem tickList = 1;
  total_size += 1UL * this->_internal_ticklist_size();
  for (const auto& msg : this->_internal_ticklist()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PushTickNotify::_class_data_ = {
    PushTickNotify::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PushTickNotify::GetClassData() const {
  return &_class_data_;
}

void PushTickNotify::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PushTickNotify*>(&to_msg);
  auto& from = static_cast<const PushTickNotify&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Quote.PushTickNotify)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_ticklist()->MergeFrom(
      from._internal_ticklist());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PushTickNotify::CopyFrom(const PushTickNotify& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Quote.PushTickNotify)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PushTickNotify::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PushTickNotify::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PushTickNotify::InternalSwap(PushTickNotify* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.ticklist_.InternalSwap(&other->_impl_.ticklist_);
}

::google::protobuf::Metadata PushTickNotify::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_notify_2fQuotePushTickNotify_2eproto_getter, &descriptor_table_notify_2fQuotePushTickNotify_2eproto_once,
      file_level_metadata_notify_2fQuotePushTickNotify_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Quote
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
