// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgType.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MsgType_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MsgType_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021011 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MsgType_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MsgType_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MsgType_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

enum PBMsgType : int {
  InvalidMsgType = 0,
  HeartbeatMsgType = 1,
  QuoteSubscribeTickMsgType = 2,
  QuoteUnsubscribeTickMsgType = 3,
  QuotePushTickMsgType = 4,
  PBMsgType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PBMsgType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PBMsgType_IsValid(int value);
constexpr PBMsgType PBMsgType_MIN = InvalidMsgType;
constexpr PBMsgType PBMsgType_MAX = QuotePushTickMsgType;
constexpr int PBMsgType_ARRAYSIZE = PBMsgType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PBMsgType_descriptor();
template<typename T>
inline const std::string& PBMsgType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PBMsgType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PBMsgType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PBMsgType_descriptor(), enum_t_value);
}
inline bool PBMsgType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PBMsgType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PBMsgType>(
    PBMsgType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::PBMsgType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PBMsgType>() {
  return ::PBMsgType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MsgType_2eproto
